#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x102C2C17498D6B9E (i.tkomiya@gmail.com)
#
Name     : sphinxcontrib-qthelp
Version  : 1.0.2
Release  : 9
URL      : https://files.pythonhosted.org/packages/0c/f0/690cd10603e3ea8d184b2fffde1d965dd337b87a1d5f7625d0f6791094f4/sphinxcontrib-qthelp-1.0.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/0c/f0/690cd10603e3ea8d184b2fffde1d965dd337b87a1d5f7625d0f6791094f4/sphinxcontrib-qthelp-1.0.2.tar.gz
Source1  : https://files.pythonhosted.org/packages/0c/f0/690cd10603e3ea8d184b2fffde1d965dd337b87a1d5f7625d0f6791094f4/sphinxcontrib-qthelp-1.0.2.tar.gz.asc
Summary  : No summary provided
Group    : Development/Tools
License  : BSD-2-Clause
Requires: sphinxcontrib-qthelp-license = %{version}-%{release}
Requires: sphinxcontrib-qthelp-python = %{version}-%{release}
Requires: sphinxcontrib-qthelp-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
sphinxcontrib-qthelp is a sphinx extension which outputs QtHelp document.

Home-page: http://sphinx-doc.org/
Author: Georg Brandl
Author-email: georg@python.org
License: BSD
Download-URL: https://pypi.org/project/sphinxcontrib-qthelp/
Description: 
        sphinxcontrib-qthelp is a sphinx extension which outputs QtHelp document.
        
Platform: any
Classifier: Development Status :: 5 - Production/Stable
Classifier: Environment :: Console
Classifier: Environment :: Web Environment
Classifier: Intended Audience :: Developers
Classifier: Intended Audience :: Education
Classifier: License :: OSI Approved :: BSD License
Classifier: Operating System :: OS Independent
Classifier: Programming Language :: Python
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
Classifier: Programming Language :: Python :: 3.7
Classifier: Framework :: Sphinx
Classifier: Framework :: Sphinx :: Extension
Classifier: Topic :: Documentation
Classifier: Topic :: Documentation :: Sphinx
Classifier: Topic :: Text Processing
Classifier: Topic :: Utilities
Requires-Python: >=3.5
Provides-Extra: test

%package license
Summary: license components for the sphinxcontrib-qthelp package.
Group: Default

%description license
license components for the sphinxcontrib-qthelp package.


%package python
Summary: python components for the sphinxcontrib-qthelp package.
Group: Default
Requires: sphinxcontrib-qthelp-python3 = %{version}-%{release}

%description python
python components for the sphinxcontrib-qthelp package.


%package python3
Summary: python3 components for the sphinxcontrib-qthelp package.
Group: Default
Requires: python3-core
Provides: pypi(sphinxcontrib-qthelp)

%description python3
python3 components for the sphinxcontrib-qthelp package.


%prep
%setup -q -n sphinxcontrib-qthelp-1.0.2
cd %{_builddir}/sphinxcontrib-qthelp-1.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582919151
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sphinxcontrib-qthelp
cp %{_builddir}/sphinxcontrib-qthelp-1.0.2/LICENSE %{buildroot}/usr/share/package-licenses/sphinxcontrib-qthelp/fc88bdd02ddfd29b245693fb34c3a9e6feee3dab
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sphinxcontrib-qthelp/fc88bdd02ddfd29b245693fb34c3a9e6feee3dab

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
